include(":features:dragonball_details")
include(":features:dragonball_favorites")
include(":features:dragonball_list")
include(":libraries:ui-components")
include(":libraries:local")
include(":libraries:navigator")
include(":libraries:base")
include(":libraries:remote")
include(":app")
rootProject.name = "DragonBall Modularization"