package com.jaimegc.dragonballmodularization.features.dragonball_details.presentation

import android.os.Bundle
import androidx.navigation.NavArgs
import java.lang.IllegalArgumentException

/**
 *  This class is not autogenerated because we are not in the home module
 */
class DragonBallDetailsFragmentArgs(
    val dragonBallId: Long
) : NavArgs {
    fun toBundle(): Bundle {
        val result = Bundle()
        result.putLong("dragonball_id", this.dragonBallId)

        return result
    }

    companion object {
        @JvmStatic
        fun fromBundle(bundle: Bundle): DragonBallDetailsFragmentArgs {
            bundle.classLoader = DragonBallDetailsFragmentArgs::class.java.classLoader
            val __dragonBallId: Long
            if (bundle.containsKey("dragonball_id")) {
                __dragonBallId = bundle.getLong("dragonball_id")
            } else {
                throw IllegalArgumentException("Required argument \"dragonball_id\" is missing and does not have an android:defaultValue")
            }

            return DragonBallDetailsFragmentArgs(__dragonBallId)
        }
    }
}